library(forecast)
library(rminer)
library(seastests)

reshow=function(label="",Y,Pred,metric="MAE",PLOT=TRUE)
{
  main=paste(label,metric,":",round(mmetric(Y,Pred,metric=metric),digits=1))
  LEG=c("target",paste(label,"pred."))
  if(PLOT)mgraph(Y,Pred,graph="REG",main=main,Grid=12,col=c("black","blue"),leg=list(pos="topleft",leg=LEG))
  else cat(main,"\n")
}

ba=read.table("baltimore.csv",header=TRUE,sep=",")
TS=ba[,3]

K=7
# statistical tests
ST=combined_test(TS,freq=K)$Pval
cat("K=",K," p-values near zero (<0.05):\n")
print(ST)
acf(TS,lag.max=20)

L=length(TS)
NTS=K # number of predictions
H=NTS # from 1 to H ahead

# code below uses library(forecast)
LTR=L-H
TR=ts(TS[1:LTR],frequency=K)
plot(TR)

Y=TS[(LTR+1):L]

print("HoltWinters")
HW=HoltWinters(TR)
print(HW)
plot(HW)
print("HoltWinters forecasts:")
F1=forecast(HW,h=H)
Pred1=F1$mean[1:H]
reshow("HW",Y,Pred1,"MAE") # Mean Absolute Error

# code below uses library(rminer)
d=CasesSeries(TS,c(1,7,8))
print(summary(d))
hd=holdout(d$y,ratio=NTS,mode="order")
LD=nrow(d)
print("LinearRegression/LinearModel")
LM=fit(y~.,d[hd$tr,],model="lm")
print(LM@object)
init=LD-H+1
F2=lforecast(LM,d,start=init,horizon=H)
Pred2=F2
reshow("LM",Y,Pred2,metric="MAE")

# reshow rehashed by Claude
# Prompt used:
# "In addition to MAE, what more metrics can I use to better compare the Holt-Winters method with linear regression?"
reshow = function(label="", Y, Pred, srange, PLOT=TRUE) {
  mae   = mmetric(Y, Pred, metric="MAE")
  nmae  = mmetric(Y, Pred, metric="NMAE",  val=srange)
  rmse  = mmetric(Y, Pred, metric="RMSE")
  rrse  = mmetric(Y, Pred, metric="RRSE")
  r2    = mmetric(Y, Pred, metric="R22")
  mape  = mmetric(Y, Pred, metric="MAPE")
  
  cat(label, "|\n")
  cat("  MAE :", round(mae,  digits=2), "\n")
  cat("  NMAE:", round(nmae, digits=1), "%\n")
  cat("  RMSE:", round(rmse, digits=2), "\n")
  cat("  RRSE:", round(rrse, digits=3), "\n")
  cat("  R2  :", round(r2,   digits=3), "\n")
  cat("  MAPE:", round(mape, digits=1), "%\n")
  
  if (PLOT) {
    main = paste(label, "MAE:", round(mae, 1), "| NMAE:", round(nmae, 1), "%")
    LEG  = c("target", paste(label, "pred."))
    mgraph(Y, Pred, graph="REG", main=main, Grid=12,
           col=c("black","blue"), leg=list(pos="topleft", leg=LEG))
  }
}

srange = diff(range(TS))

reshow("HW", Y, Pred1, srange)
reshow("LM", Y, Pred2, srange)

# comparative graph generated by Claude, based on previous work
# Prompt used:
# "Thank you so much! Now, could I do something similar as I did in the previous file I attached, but now only comparing two models, Holt-Winters and linear regression? The relevant snippet of the previous file is the following:"
print("Graph with HW and LM predictions (multi step-ahead):")
plot(1:length(Y), Y, ylim=c(min(Pred1, Pred2, Y), max(Pred1, Pred2, Y)), type="b", col="black")
lines(Pred1, type="b", col="blue",   pch=2)
lines(Pred2, type="b", col="red",    pch=3)
legend("topright", c("Original","HW","LM"), pch=c(1,2,3), col=c("black","blue","red"))